using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ConquerTheCity.Inputs
{
    public class Inputs : MonoBehaviour
    {
        [SerializeField] Camera gameCamera;
        //[SerializeField] float _distance = 0f;

        //Input.GetMouseButtonDown(0) ilk t覺klama an覺

        //if (Input.GetMouseButton(0)) t覺klama devam ediyor

        //if (Input.GetMouseButtonUp(0)) t覺klama bitti

        private void Update()
        {
            if(Input.GetMouseButtonDown(0))
            {
                RaycastHit2D hit = Physics2D.Raycast(gameCamera.ScreenToWorldPoint(Input.mousePosition), Vector2.zero);
                
                if (hit.collider.CompareTag("Tower"))
                {
                    Debug.Log ("Target name: " + hit.collider.name);
                }
                else 
                {
                    Debug.Log ("Target name: " + hit.collider.name);
                }
            }

        }
    }   
}

